#ifndef FPS_PHYSICS_GPU_LAYOUT_H
#define FPS_PHYSICS_GPU_LAYOUT_H

enum FpsGpuBufferSlot {
    FPS_GPU_BUFFER_PARTICLE = 0,
    FPS_GPU_BUFFER_CORRECTION = 1,
    FPS_GPU_BUFFER_CELL = 2,
    FPS_GPU_BUFFER_SIM_ID = 3,
    FPS_GPU_BUFFER_VOXEL = 4,
    FPS_GPU_BUFFER_HASH_HEAD = 5,
    FPS_GPU_BUFFER_HASH_NEXT = 6,
    FPS_GPU_BUFFER_STATIC_CELL = 7,
    FPS_GPU_BUFFER_TETHER = 8,
    FPS_GPU_BUFFER_COLLISION_META = 9,
    FPS_GPU_BUFFER_STATIC_COLLIDER = 10,
    FPS_GPU_BUFFER_REFCOUNT = 11,
    FPS_GPU_BUFFER_CONTROL = 12,
    FPS_GPU_BUFFER_CLONE_PARENT = 13,
    FPS_GPU_BUFFER_DISPATCH = 14,
    FPS_GPU_BUFFER_TOPOLOGY = 15,
    FPS_GPU_BUFFER_COUNT = 16
};

enum GpuPipelineMode {
    GPU_MODE_RESET = 0,
    GPU_MODE_INTEGRATE = 1,
    GPU_MODE_HASH_CLEAR = 2,
    GPU_MODE_HASH_BUILD = 3,
    GPU_MODE_SCENE_COLLISIONS = 4,
    GPU_MODE_PAIR_COLLISIONS = 5,
    GPU_MODE_APPLY = 6,
    GPU_MODE_VGS = 7,
    GPU_MODE_STATIC_COLLISIONS = 8,
    GPU_MODE_BREAK_MASK = 9,
    GPU_MODE_FINALIZE_PARTICLES = 10,
    GPU_MODE_FINALIZE_VOXELS = 11,
    GPU_MODE_SPLIT_BREAKS = 12,
    GPU_MODE_PREPARE_INDIRECT = 13,
    GPU_MODE_WAKE_GATHER = 14,
    GPU_MODE_WAKE_APPLY = 15,
    GPU_MODE_TOPOLOGY_REBUILD_SERIAL = 16,
    GPU_MODE_VGS_LIST_PREPARE = 17,
    GPU_MODE_VGS_LIST_BUILD = 18,
    GPU_MODE_VGS_LIST_FINALIZE = 19,
    GPU_MODE_VGS_APPLY = 20
};

enum FpsGpuControlFlag {
    FPS_GPU_CONTROL_OVERFLOW = 1,
    FPS_GPU_CONTROL_TOPOLOGY_DIRTY = 2
};

#endif
