#ifndef FPS_PHYSICS_GPU_LAYOUT_H
#define FPS_PHYSICS_GPU_LAYOUT_H

enum FpsGpuBufferSlot {
    FPS_GPU_BUFFER_PARTICLE = 0,
    FPS_GPU_BUFFER_CORRECTION = 1,
    FPS_GPU_BUFFER_CELL = 2,
    FPS_GPU_BUFFER_SIM_ID = 3,
    FPS_GPU_BUFFER_VOXEL = 4,
    FPS_GPU_BUFFER_HASH_HEAD = 5,
    FPS_GPU_BUFFER_HASH_NEXT = 6,
    FPS_GPU_BUFFER_STATIC_CELL = 7,
    FPS_GPU_BUFFER_TETHER = 8,
    FPS_GPU_BUFFER_COLLISION_META = 9,
    FPS_GPU_BUFFER_STATIC_COLLIDER = 10,
    FPS_GPU_BUFFER_REFCOUNT = 11,
    FPS_GPU_BUFFER_CONTROL = 12,
    FPS_GPU_BUFFER_CLONE_PARENT = 13,
    FPS_GPU_BUFFER_DISPATCH = 14,
    FPS_GPU_BUFFER_TOPOLOGY = 15,
    FPS_GPU_BUFFER_AMR_STATE = 16,
    FPS_GPU_BUFFER_AMR_SCRATCH = 17,
    FPS_GPU_BUFFER_AMR_CONTROL = 18,
    FPS_GPU_BUFFER_AABB_STATE = 19,
    FPS_GPU_BUFFER_AABB_OWNER = 20,
    FPS_GPU_BUFFER_AABB_CONTROL = 21,
    FPS_GPU_BUFFER_PARTIAL = 22,
    FPS_GPU_BUFFER_COUNT = 23
};

enum GpuPipelineMode {
    GPU_MODE_RESET = 0,
    GPU_MODE_INTEGRATE = 1,
    GPU_MODE_HASH_CLEAR = 2,
    GPU_MODE_HASH_BUILD = 3,
    GPU_MODE_SCENE_COLLISIONS = 4,
    GPU_MODE_PAIR_COLLISIONS = 5,
    GPU_MODE_APPLY = 6,
    GPU_MODE_VGS = 7,
    GPU_MODE_STATIC_COLLISIONS = 8,
    GPU_MODE_BREAK_MASK = 9,
    GPU_MODE_FINALIZE_PARTICLES = 10,
    GPU_MODE_FINALIZE_VOXELS = 11,
    GPU_MODE_SPLIT_BREAKS = 12,
    GPU_MODE_PREPARE_INDIRECT = 13,
    GPU_MODE_WAKE_GATHER = 14,
    GPU_MODE_WAKE_APPLY = 15,
    GPU_MODE_TOPOLOGY_REBUILD_SERIAL = 16,
    GPU_MODE_HIERARCHY_MASK = 17,
    GPU_MODE_AMR_CLEAR = 18,
    GPU_MODE_AMR_SAMPLE = 19,
    GPU_MODE_AMR_SAMPLE_COMPLETE = 20,
    GPU_MODE_AMR_SELECT = 21,
    GPU_MODE_AMR_RESOLVE = 22,
    GPU_MODE_AMR_TRANSITION_CLEAR = 23,
    GPU_MODE_AMR_TRANSITION_SCATTER = 24,
    GPU_MODE_AMR_TRANSITION_APPLY = 25,
    GPU_MODE_AMR_TOPOLOGY_APPLY = 26,
    GPU_MODE_AMR_MASS_SCATTER = 27,
    GPU_MODE_AMR_COMPACT = 28,
    GPU_MODE_AMR_COMPILE = 29,
    GPU_MODE_AMR_PREPARE_INDIRECT = 30,
    GPU_MODE_AMR_DORMANT_SCATTER = 31,
    GPU_MODE_AABB_CLEAR = 32,
    GPU_MODE_AABB_BOUNDS = 33,
    GPU_MODE_AABB_HASH_BUILD = 34,
    GPU_MODE_AABB_COLLISIONS = 35,
    GPU_MODE_AABB_STATIC_COLLISIONS = 36,
    GPU_MODE_AABB_REDUCE = 37,
    GPU_MODE_AABB_TREE_COLLISIONS = 38,
    GPU_MODE_AMR_SPHERE_SETUP = 39,
    GPU_MODE_AMR_SPHERE_TREE_COLLISIONS = 40,
    GPU_MODE_AMR_SPHERE_STATIC_COLLISIONS = 41
};

enum FpsGpuControlFlag {
    FPS_GPU_CONTROL_OVERFLOW = 1,
    FPS_GPU_CONTROL_TOPOLOGY_DIRTY = 2,
    FPS_GPU_CONTROL_BREAK_OCCURRED = 4
};

#endif
