#ifndef FPS_PHYSICS_GPU_LAYOUT_H
#define FPS_PHYSICS_GPU_LAYOUT_H

enum FpsGpuBufferSlot {
    FPS_GPU_BUFFER_PARTICLE = 0,
    FPS_GPU_BUFFER_CORRECTION = 1,
    FPS_GPU_BUFFER_CELL = 2,
    FPS_GPU_BUFFER_SIM_ID = 3,
    FPS_GPU_BUFFER_VOXEL = 4,
    FPS_GPU_BUFFER_HASH_HEAD = 5,
    FPS_GPU_BUFFER_HASH_NEXT = 6,
    FPS_GPU_BUFFER_STATIC_CELL = 7,
    FPS_GPU_BUFFER_TETHER = 8,
    FPS_GPU_BUFFER_COLLISION_META = 9,
    FPS_GPU_BUFFER_STATIC_COLLIDER = 10,
    FPS_GPU_BUFFER_REFCOUNT = 11,
    FPS_GPU_BUFFER_CONTROL = 12,
    FPS_GPU_BUFFER_CLONE_PARENT = 13,
    FPS_GPU_BUFFER_DISPATCH = 14,
    FPS_GPU_BUFFER_TOPOLOGY = 15,
    FPS_GPU_BUFFER_DEPENDENCY_HEADER = 16,
    FPS_GPU_BUFFER_DEPENDENCY_ENTRY = 17,
    FPS_GPU_BUFFER_STATIC_MAPPED_CORRECTION = 18,
    FPS_GPU_BUFFER_RENDER_VOXEL = 19,
    FPS_GPU_BUFFER_RENDER_MATRIX = 20,
    FPS_GPU_BUFFER_COLLISION_BATCH = 21,
    FPS_GPU_BUFFER_FLOOR_ISLAND = 22,
    FPS_GPU_BUFFER_FLOOR_CONTROL_ID = 23,
    FPS_GPU_BUFFER_FLOOR_CONTACT = 24,
    FPS_GPU_BUFFER_FLOOR_CONTROL_MAP = 25,
    FPS_GPU_BUFFER_COUNT = 26
};

enum GpuPipelineMode {
    GPU_MODE_RESET = 0,
    GPU_MODE_INTEGRATE = 1,
    GPU_MODE_HASH_CLEAR = 2,
    GPU_MODE_HASH_BUILD = 3,
    GPU_MODE_SCENE_COLLISIONS = 4,
    GPU_MODE_PAIR_COLLISIONS = 5,
    GPU_MODE_APPLY = 6,
    GPU_MODE_VGS = 7,
    GPU_MODE_STATIC_COLLISIONS = 8,
    GPU_MODE_BREAK_MASK = 9,
    GPU_MODE_FINALIZE_PARTICLES = 10,
    GPU_MODE_FINALIZE_VOXELS = 11,
    GPU_MODE_SPLIT_BREAKS = 12,
    GPU_MODE_PREPARE_INDIRECT = 13,
    GPU_MODE_WAKE_GATHER = 14,
    GPU_MODE_WAKE_APPLY = 15,
    GPU_MODE_TOPOLOGY_REBUILD_SERIAL = 16,
    GPU_MODE_REFRESH_DEPENDENCIES = 17,
    GPU_MODE_FINALIZE_DEPENDENCIES = 18,
    GPU_MODE_LIFT_GREEDY_FLOOR = 19,
    GPU_MODE_RESET_STATIC_MAPPED = 20,
    GPU_MODE_APPLY_STATIC_MAPPED = 21,
    GPU_MODE_BUILD_RENDER_MATRICES = 22,
    GPU_MODE_GREEDY_FLOOR_ISLANDS = 23,
    GPU_MODE_ATTACHMENTS = 24,
    GPU_MODE_ATTACHMENTS_SERIAL = 25,
    GPU_MODE_ATTACHMENTS_FINAL = 26,
    GPU_MODE_STATIC_GREEDY_BATCH_BASE = 100,
    GPU_MODE_GREEDY_FLOOR_BATCH_BASE = 1000
};

enum { FPS_GPU_MAX_FLOOR_ISLAND_CONTROLS = 512 };

enum FpsGpuDependencyFlag {
    FPS_GPU_DEPENDENCY_MAPPED = 1,
    FPS_GPU_DEPENDENCY_PARENT_USE = 2,
    FPS_GPU_DEPENDENCY_OWNER_CONTROL = 4,
    FPS_GPU_DEPENDENCY_ATTACHMENT = 8
};

enum FpsGpuControlFlag {
    FPS_GPU_CONTROL_OVERFLOW = 1,
    FPS_GPU_CONTROL_TOPOLOGY_DIRTY = 2
};

#endif
