name: Build FPS Game
permissions:
  contents: read
  actions: write
on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: sudo apt update && sudo apt install -y libsdl2-dev libsdl2-ttf-dev libglu1-mesa-dev libsdl2-image-dev
      - name: Compile for Linux
        run: gcc fps_game.c -o fps_game $(sdl2-config --cflags --libs) -lGL -lGLU -lSDL2_ttf -lm
      - name: Upload Linux build
        uses: actions/upload-artifact@v4
        with:
          name: fps_game-linux
          path: fps_game

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup MSYS2 and dependencies
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: |
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-SDL2
            mingw-w64-x86_64-SDL2_ttf
            mingw-w64-x86_64-SDL2_image
      - name: Compile for Windows
        shell: msys2 {0}
        run: |
          gcc fps_game.c -o fps_game.exe \
            -I/mingw64/include \
            -L/mingw64/lib \
            -lmingw32 -lSDL2main -lSDL2 -lSDL2_ttf \
            -lopengl32 -lglu32 \
            -lm
      - name: Upload Windows build
        uses: actions/upload-artifact@v4
        with:
          name: fps_game-win
          path: fps_game.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install macOS dependencies
        run: brew install sdl2 sdl2_ttf sdl2_image
      - name: Compile for macOS (universal binary)
        run: |
          prefix=$(brew --prefix)

          gcc -arch x86_64 fps_game.c -o fps_game_x86 \
            -I${prefix}/include \
            $(sdl2-config --cflags --libs) \
            -lSDL2_ttf -lSDL2_image \
            -framework OpenGL -lm

          gcc -arch arm64 fps_game.c -o fps_game_arm \
            -I${prefix}/include \
            $(sdl2-config --cflags --libs) \
            -lSDL2_ttf -lSDL2_image \
            -framework OpenGL -lm

          lipo -create -output fps_game fps_game_x86 fps_game_arm
      - name: Upload macOS build
        uses: actions/upload-artifact@v4
        with:
          name: fps_game-mac
          path: fps_game
